export const ADD_NUMBER = "ADD_NUMBER";
export const REMOVE_NUMBER = "REMOVE_NUMBER";
export const SORT_NUMBERS = "SORT_NUMBERS";
export const ADD_STORED_NUMBERS = "ADD_STORED_NUMBERS";
export const REMOVE_ALL_NUMBERS = "REMOVE_ALL_NUMBERS";
